FROM golang:1.19 as build
WORKDIR /app

ENV GOPRIVATE=github.com/jjh930301

ARG GITACCOUNT
ARG GITTOKEN

# install git
RUN apk add --no-cache git 
# private repo config
RUN git config --global url."https://${GITACCOUNT}:${GITTOKEN}@github.com/jjh930301/needsss_common".insteadOf "https://github.com/jjh930301/needsss_common"
COPY ./go.mod .
COPY ./go.sum .
RUN go mod download
COPY . .
RUN go build -o /build/app .
FROM golang:1.19 as run
COPY --from=build /build/app /app
ENTRYPOINT [ "/app" ]
